name: Go

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out reg-payment-cncrd-adapter (primary)
      uses: actions/checkout@v2
      with:
        path: ./reg-payment-cncrd-adapter

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Build reg-payment-cncrd-adapter (primary)
      run: go build -v ./...
      working-directory: ./reg-payment-cncrd-adapter

    - name: Test reg-payment-cncrd-adapter (primary)
      run: go test -v ./...
      working-directory: ./reg-payment-cncrd-adapter
